#!/usr/bin/env ruby
# 5. Modify the previous program such that only multiples of three or five are
# considered in the sum, eg. 3,5,6,9,10,12,15 for n = 17

def sum_of_all_numbers(number)
  i = 0
  numbers = []

  while i < number
    numbers.push(i) if i % 3 == 0 || i % 5 == 0
    i += 1
  end

  puts numbers.inject(:+)

end

print "Please give me a number "
number = sum_of_all_numbers gets.chomp.to_i